colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
smartTOC = true
defaultBackgroundImage = "optimus.jpg"

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = false
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts/"
cardView = "yes"
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "."

[article]
showDate = true
showViews = true
showLikes = false
showDateOnlyInArticle = true
showDateUpdated = true
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = true
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = true
showWordCount = true
showZenMode = true

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = true
showViews = true
showLikes = true
showTableOfContents = true
showCards = true
orderByWeight = true
groupByYear = true
cardView = true
cardViewScreenWidth = true
constrainItemsWidth = true

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = true
showViews = true
showLikes = true
showTableOfContents = true
cardView = true

[term]
showHero = true
showBreadcrumbs = true
showViews = true
showLikes = true
showTableOfContents = true
groupByYear = true
cardView = true
cardViewScreenWidth = true

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]

[rssnext]
